[package]
name = "rubik"
version = "0.7.0"
edition = "2021"

[dependencies]
winit = "0.29.10"
env_logger = "0.10"
log = "0.4"
wgpu = "^22.0.0"
bytemuck = { version = "1.12", features = ["derive"] }
pollster = "0.3.0"
glam = { version = "0.24.2", features = ["bytemuck"] }
tween = { version = "2.0.1", features = ["glam"] }
rand = "0.8.5"
